spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-atguigu-dev1
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-atguigu-test1
        #开发和测试
